#!/bin/bash

arg=$1
emulator_dir="/home/bairgl/Android/Sdk/emulator"
file="${HOME}/Documents/emulators.txt"

function get_emulators()
{
	echo -e "\n\033[33mHere is the list of currently used emulators:\033[0m"
	echo -e "\033[32m=============================================\033[0m\n"
	cat ${file}
	echo -e "\n"
}

if [[ ${arg} == "" ]]; then
	echo -e "
	usage = a-emu <DEVICE>
	\n"
	exit 1
elif [[ ${arg} == "show" ]]; then
	get_emulators
else
	echo -e "\n\033[32mStarting device:\033[0m\033[33m ${arg}\033[0m\033[32m ...\033[0m\n"
	${emulator_dir}/emulator -avd ${arg} -use-system-libs
	echo "${arg}" >> ${HOME}/Documents/emulators.txt
fi

